services:
  - type: web
    name: spring-boot-app
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: GITHUB_USERNAME
        sync: false
      - key: GITHUB_TOKEN
        sync: false
    buildArgs:
        GITHUB_USERNAME: ${GITHUB_USERNAME}
        GITHUB_TOKEN: ${GITHUB_TOKEN}