#server config
spring.application.name=dashboard_oauth
server.port=8081

# mongo db
spring.mongodb.uri=mongodb+srv://hugovrna:DoPrdele-457x@shop-db.jhj5pms.mongodb.net/dashboard_oauth?retryWrites=true&w=majority

# grafana
grafana.apiKey=1358926:glc_eyJvIjoiMTU1NjQ5OSIsIm4iOiJkYXNoYm9hcmQtc3ByaW50LWFwaSIsImsiOiJ0WDhmOGo0NURYRjhUQ1Q4NXM2eHo2TzUiLCJtIjp7InIiOiJwcm9kLWV1LWNlbnRyYWwtMCJ9fQ==
grafana.url=https://logs-prod-039.grafana.net/loki/api/v1/push

#JWT
jwt.secret=pHop9CyAIzw/Y6OHA3DXkZAFJxWRht2d2ROClZQNbSw=
jwt.expiration=86400000
spring.security.oauth2.secret=9f27d054a8330e42439ce2126c6a7a52c9624754070e6ffeb96cbe0507a5e57b

#resend
resend.apiKey=re_SmLNRVRp_3mdHEtJGsH8PyR8UNMiLaavo

#default email values
email.baseUrl=http://localhost:3000
email.fromAddress=acme@dashboard.run.place
email.verificationTokenExpirationMs=86400000
email.passwordResetTokenExpirationMs=3600000

# R2 configuration
r2.accessKeyId=ee4cdccb93897cdf60abd2bbddc07adc
r2.secretAccessKey=314993bbb1bb63e7c1a5c3305f8736acfd9c4afa9a9d4f8b1b34c20e989e8604
r2.accountId=a50c238beb2f795d24295b595b11fddd
r2.bucketName=dashboard-auth-user-images
r2.publicUrl=https://pub-7a881e6eb64d4bbebf6e92f42581adb8.r2.dev

# Lockout configuration
login.maxFailedAttempts=5