spring.application.name=dashboard_oauth
# OAuth2 Client Registration (example with Google)
spring.security.oauth2.client.registration.google.client-id=your-google-client-id
spring.security.oauth2.client.registration.google.client-secret=your-google-client-secret
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.data.mongodb.uri=mongodb+srv://hugovrna:DoPrdele-457x@shop-db.jhj5pms.mongodb.net/dashboard?retryWrites=true&w=majority