spring.application.name=dashboard_oauth
spring.data.mongodb.username=hugovrna
spring.data.mongodb.password=DoPrdele-457x
spring.data.mongodb.database=dashboard_oauth
spring.data.mongodb.uri=mongodb+srv://hugovrna:DoPrdele-457x@shop-db.jhj5pms.mongodb.net/dashboard_oauth?retryWrites=true&w=majority
JWT.SECRET=pHop9CyAIzw/Y6OHA3DXkZAFJxWRht2d2ROClZQNbSw=
JWT.EXPIRATION=86400000
server.port=8081
spring.security.oauth2.secret=9f27d054a8330e42439ce2126c6a7a52c9624754070e6ffeb96cbe0507a5e57b