package com.dashboard.oauth.model.enums;

public enum ActivityEventType {
    USER_REGISTERED,
    USER_LOGGED_IN,
    EMAIL_VERIFIED,
    USER_LOGGED_OUT,
    TOKEN_REFRESHED,
    PASSWORD_RESET_REQUESTED,
    PASSWORD_RESET,
    ROLE_ADDED_TO_USER,
    GRANT_ADDED,
    GRANT_REMOVED,
    ROLE_ADDED,
    ROLE_REMOVED,
    GRANT_ADDED_TO_ROLE,
    GRANT_REMOVED_FROM_ROLE,
    OAUTH_CLIENT_CREATED,
    OAUTH_CLIENT_DELETED
}
